name: Frontend Deployment

on:
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'

env:
  BUCKET_NAME: ${{ secrets.GCP_PROJECT_ID }}-frontend-assets

jobs:
  test:
    name: 'Test Frontend'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run linter
      run: npm run lint

    - name: Run type check
      run: npm run check

    - name: Build application
      run: npm run build

    - name: Run tests
      run: npm run test

  deploy:
    name: 'Deploy to Cloud Storage'
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Upload to Cloud Storage
      uses: google-github-actions/upload-cloud-storage@v2
      with:
        path: ./frontend/build
        destination: ${{ env.BUCKET_NAME }}
        parent: false
        gzip_in_flight: true

    - name: Set up URL rewrite for SPA
      run: |
        # Create a 404.html file that redirects to index.html for SPA routing
        echo '<!DOCTYPE html>
        <html>
        <head>
        <title>Page Not Found</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <script>
        // Single Page Applications for GitHub Pages
        // https://github.com/rafrex/spa-github-pages
        // Copyright (c) 2016 Rafael Pedicini, licensed under the MIT License
        // ----------------------------------------------------------------------
        // This script takes the current URL and converts the path and query string into
        // just a query string, and then redirects the browser back to the root of the
        // application.
        (function(l) {
          if (l.search[1] === "/" ) {
            var decoded = decodeURIComponent(l.search.slice(1));
            window.history.replaceState(null, null, l.pathname.slice(0, -1) + decoded + l.hash);
          }
        }(window.location))
        </script>
        </head>
        <body>
        Redirecting...
        </body>
        </html>' > ./frontend/build/404.html
